# Generated by Django 2.1.5 on 2019-01-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='codigo_barras',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='codigo_produto',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
