# Generated by Django 2.1.5 on 2019-01-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkraft', '0002_auto_20190117_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='estoque_atual',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='estoque_minimo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='observacoes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtos',
            name='codigo_barras',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='codigo_produto',
            field=models.IntegerField(unique=True),
        ),
    ]
