# Generated by Django 2.1.5 on 2019-01-17 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appkraft', '0003_auto_20190117_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='create_data',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
