# Generated by Django 2.1.5 on 2019-01-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkraft', '0004_auto_20190117_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='marca',
            field=models.CharField(default='Rubiks', max_length=150),
            preserve_default=False,
        ),
    ]
