# Generated by Django 2.1.5 on 2019-01-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkraft', '0005_produtos_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='appkraft'),
        ),
    ]
